---
name: "Checkin"
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "Setup node"
        uses: actions/setup-node@v3
        with:
          node-version: "latest"

      - name: "npm ci"
        run: npm ci

      - name: "lint"
        run: npm run lint

      - name: "build"
        run: npm run build
